apiVersion: v1
kind: ServiceAccount
metadata:
  name: met-controller
  namespace: kube-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: met-controller
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/status", "pods/binding", "nodes", "services"]
    verbs: ["get", "list", "watch", "create"]
  - apiGroups: ["metrics.k8s.io"]
    resources: ["nodes", "pods"]
    verbs: ["get", "list"]
  - apiGroups: ["workflow.example.com"] 
    resources: ["dags"]                 
    verbs: ["get", "list", "watch"]     

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: met-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: met-controller
subjects:
  - kind: ServiceAccount
    name: met-controller
    namespace: kube-system
