apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: retina
  namespace: kube-system
  labels:
    app: retina
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: retina
  endpoints:
  - port: "10093"
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
    relabelings:
    - sourceLabels: [__meta_kubernetes_pod_node_name]
      targetLabel: instance
      replacement: $1
