apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: pathload-receiver
spec:
  selector:
    matchLabels:
      app: pathload-receiver
  template:
    metadata:
      labels:
        app: pathload-receiver
    spec:
      hostNetwork: true
      containers:
      - name: pathload-d
        image: pathload-d:latest
        imagePullPolicy: IfNotPresent
        command: ["/usr/local/bin/entrypoint.sh"]
        args: ["-r"]
        env:
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: ALL_IPS
          value: "10.25.100.215,10.25.229.253,10.25.129.141,192.168.0.105"