apiVersion: v1
kind: Pod
metadata:
  name: pathload-sender
  labels:
    app.kubernetes.io/name: Sender
spec:
  hostNetwork: true
  containers:
  - name: pathload-d
    image: pathload-d:latest
    imagePullPolicy: IfNotPresent
    command: ["/usr/local/bin/entrypoint.sh"]
    args: ["-s"]
    env:
    - name: NODE_IP
      valueFrom:
          fieldRef:
            fieldPath: status.hostIP
    - name: NODE_NAME
      valueFrom:
          fieldRef:
            fieldPath: spec.nodeName
